server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    application:
      name: student
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect